name: Publish Python Package to GitHub Packages

on:
  push:
    tags: ["python-v*"]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to GitHub Packages"
        required: true
        default: true
        type: boolean

defaults:
  run:
    working-directory: ./python

env:
  # For ease of development, we make rustls default. But for release we should
  # use native TLS.
  FEATURES_FLAG: --no-default-features --features native-tls

jobs:
  validate-release-tag:
    name: Validate git tag
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: compare git tag with cargo metadata
        run: |
          PUSHED_TAG=${GITHUB_REF##*/}
          CURR_VER=$( grep version Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"' )
          if [[ "${PUSHED_TAG}" != "python-v${CURR_VER}" ]]; then
            echo "Cargo metadata has version set to ${CURR_VER}, but got pushed tag ${PUSHED_TAG}."
            exit 1
          fi

  build-package:
    name: Build Python Package
    runs-on: ubuntu-latest
    needs: validate-release-tag
    if: always() && (needs.validate-release-tag.result == 'success' || github.event_name == 'workflow_dispatch')

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build wheel
        uses: messense/maturin-action@v1
        with:
          maturin-version: v1.6.0
          target: x86_64-unknown-linux-gnu
          command: build
          args: --release -m python/Cargo.toml ${{ env.FEATURES_FLAG }}
          before-script-linux: yum install -y perl-IPC-Cmd

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: python/target/wheels/

  publish-to-github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: build-package
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Install twine
        run: pip install twine

      - name: Publish package to GitHub Packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m twine upload --repository-url https://pypi.pkg.github.com/${{ github.repository_owner }}/ dist/*
