name: Publish to GitHub Packages

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./python

jobs:
  validate-release-tag:
    name: Validate git tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Check if pre-release
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            echo "Skipping pre-release"
            exit 0
          fi
      - name: compare git tag with cargo metadata
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          CURR_VER=$( grep version Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"' )
          EXPECTED_TAG="v${CURR_VER}"
          if [[ "${RELEASE_TAG}" != "${EXPECTED_TAG}" ]]; then
            echo "Cargo metadata has version set to ${CURR_VER}, but got release tag ${RELEASE_TAG}."
            echo "Expected tag: ${EXPECTED_TAG}"
            exit 1
          fi

  release-github-packages-mac:
    needs: validate-release-tag
    name: GitHub Packages release on Mac
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: macos-14
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build with maturin
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          command: build
          args: --release -m python/Cargo.toml
        env:
          # Prevent maturin from trying to upload automatically
          MATURIN_REPOSITORY_URL: ""
          MATURIN_USERNAME: ""
          MATURIN_PASSWORD: ""

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload ../target/wheels/*

  release-github-packages-windows:
    needs: validate-release-tag
    name: GitHub Packages release on Windows
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build with maturin
        uses: messense/maturin-action@v1
        with:
          target: x86_64-pc-windows-msvc
          command: build
          args: --release -m python/Cargo.toml
        env:
          # Prevent maturin from trying to upload automatically
          MATURIN_REPOSITORY_URL: ""
          MATURIN_USERNAME: ""
          MATURIN_PASSWORD: ""

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload ../target/wheels/*

  release-github-packages-manylinux-x86-64:
    needs: validate-release-tag
    name: GitHub Packages release manylinux-2_17 x86_64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build with maturin
        uses: messense/maturin-action@v1
        with:
          maturin-version: v1.6.0 # https://github.com/PyO3/maturin/issues/2154
          target: x86_64-unknown-linux-gnu
          command: build
          args: --release -m python/Cargo.toml
          # for openssl build
          before-script-linux: yum install -y perl-IPC-Cmd
        env:
          # Prevent maturin from trying to upload automatically
          MATURIN_REPOSITORY_URL: ""
          MATURIN_USERNAME: ""
          MATURIN_PASSWORD: ""

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload ../target/wheels/*

  release-github-packages-manylinux-217-aarch64:
    needs: validate-release-tag
    name: GitHub Packages release manylinux-2_17 aarch64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build with maturin
        uses: messense/maturin-action@v1
        with:
          target: aarch64-unknown-linux-gnu
          command: build
          args: --release -m python/Cargo.toml
          before-script-linux: |
            # We can remove this once we upgrade to 2_28.
            # https://github.com/briansmith/ring/issues/1728
            export CFLAGS_aarch64_unknown_linux_gnu="-D__ARM_ARCH=8"
        env:
          # Prevent maturin from trying to upload automatically
          MATURIN_REPOSITORY_URL: ""
          MATURIN_USERNAME: ""
          MATURIN_PASSWORD: ""

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload ../target/wheels/*

  release-github-packages-manylinux-228-aarch64:
    needs: validate-release-tag
    name: GitHub Packages release manylinux-2_28 aarch64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build with maturin
        uses: messense/maturin-action@v1
        with:
          target: aarch64-unknown-linux-gnu
          command: build
          args: --release -m python/Cargo.toml --manylinux 2_28
          before-script-linux: |
            # We can remove this once we upgrade to 2_28.
            # https://github.com/briansmith/ring/issues/1728
            export CFLAGS_aarch64_unknown_linux_gnu="-D__ARM_ARCH=8"
        env:
          # Prevent maturin from trying to upload automatically
          MATURIN_REPOSITORY_URL: ""
          MATURIN_USERNAME: ""
          MATURIN_PASSWORD: ""

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload ../target/wheels/*
