name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin twine

      - name: Build with maturin
        working-directory: ./python
        run: |
          maturin build --release -o dist

      - name: Upload wheel to GitHub Release
        working-directory: ./python
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload source distribution to GitHub Release
        working-directory: ./python
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
